#!/bin/bash

# Where in the world is bootstrap?
BOOTSTRAP_ARCHIVE="https://github.com/br0ns/bootstrap/archive/master.zip"

THISDIR="$(dirname "$(realpath "$0")")"
export BOOTSTRAP_ALL=true

# Fail on any error
set -e

# If this file does not exist it's probably because we're bootstrapping a fresh
# system.  So we download the Git repository and bootstrap from there
if [ ! -e "$THISDIR/bs.sh" ] ; then
    # Required packages
    for pkg in ca-certificates unzip wget ; do
        if ! dpkg --status $pkg >/dev/null 2>&1 ; then
            echo Installing $pkg
            sudo CHECK_PKGS_DONT_RUN=1 apt-get install --yes --no-install-recommends $pkg
        fi
    done

    echo -e "Downloading \x1b[32m$BOOTSTRAP_ARCHIVE\x1b[m => \x1b[32m$PWD/\x1b[m"
    wget "$BOOTSTRAP_ARCHIVE"
    unzip master.zip && rm master.zip
    # Overwrite this script with a symlink to it inside the downloaded repo, so
    # subsequent runs won't download it again
    BSDIR="$(realpath "$PWD"/bootstrap-master)"
    ln -sf "$BSDIR"/bootstrap "$0"
else
    BSDIR="$THISDIR"
fi

exit 0

# Go through all the step scripts and execute them
for f in $(ls "$DIR" | sort -n) ; do
    p="$DIR/$f"
    # Path must be an executable (-x) file (-f) which starts with a digit
    [[ "$f" =~ ^[0-9] ]] && [ -f "$p" ] && [ -x "$p" ] || continue
    "$p" "$@"
done

exit 0
